"""Regenerate the SI copies of the appendices (gap rule, technology, sensitivity) from the
long-version appendix files, redirecting cross-references to the PNAS main text and SI.
Revision 2 (2026-09-29): main-text figure numbers are \\ref-based; timing is SI Text 6."""
import re, os
os.chdir('/home/claude/gf/tex')
P = 'pnas/'
MAINFIG = {
 'fig:frontier': '\\ref{fig:p1}', 'fig:thin-grants': '\\ref{fig:p2}\\textit{A}', 'fig:records-rounds': '\\ref{fig:p2}\\textit{B}',
 'fig:review-value': '\\ref{fig:p2}\\textit{C}', 'fig:timing-boundary': '\\ref{fig:p3}\\textit{A}', 'fig:schedule-vs-signal': '\\ref{fig:p3}\\textit{B}',
 'fig:floor-cost': '\\ref{fig:p4}\\textit{A}', 'fig:lottery-schemes': '\\ref{fig:p4}\\textit{B}',
}
SIFIG = ['fig:targeting-value', 'fig:overtrust', 'fig:depth-schedule', 'fig:concentration', 'fig:signal-robustness', 'fig:gap-gini', 'fig:heuristics', 'fig:regime']

def convert(s):
    for lab, num in MAINFIG.items():
        s = s.replace('Figures~\\ref{%s}' % lab, 'Figs.~%s' % num)
        s = s.replace('Figure~\\ref{%s}' % lab, 'Fig.~%s' % num)
        s = re.sub(r'^\\ref\{%s\}' % re.escape(lab), 'Fig.~%s' % num, s, flags=re.M)
        s = s.replace('and~\\ref{%s}' % lab, 'and Fig.~%s' % num)
        s = s.replace('\\ref{%s}' % lab, 'Fig.~%s' % num)
    for lab in SIFIG:
        s = re.sub(r'^\\ref\{%s\}' % re.escape(lab), 'Fig.~\\\\ref{%s}' % lab, s, flags=re.M)
        s = s.replace('and~\\ref{%s}' % lab, 'and Fig.~\\ref{%s}' % lab)
    s = s.replace('Figures~', 'Figs.~').replace('Figure~', 'Fig.~')
    s = re.sub(r'\(both \\S\\ref\{sec:(optimal|review|records|egalitarian)\}\)', '(both in the main text)', s)
    s = re.sub(r'\(\\S\\ref\{sec:(optimal|review|records|egalitarian)\}\)', '(main text)', s)
    s = re.sub(r'\\S\\ref\{sec:(optimal|review|records|egalitarian)\}', 'the main text', s)
    s = s.replace('\\S\\ref{sec:model}', '\\ref{sec:model}')
    s = re.sub(r'\\[cC]ref\{sec:(model|optimal|review|records|egalitarian)\}', 'the main text', s)
    s = s.replace('and about half at Leontief.\\footnote{15.8, 47.1, and 51.4 percent. ', 'and about half at Leontief (15.8, 47.1, and 51.4 percent).\\footnote{')
    s = re.sub(r'\.\\footnote\{([^{}]*(?:\{[^{}]*\}[^{}]*)*)\}', r'. \1', s)
    s = s.replace('Appendix~\\ref{app:timing}', '\\ref{si:timing}')
    s = s.replace('Appendix~\\ref{', '\\ref{').replace('Appendices~\\ref{', '\\ref{')
    s = s.replace('\\input{fig14-heuristics}', '\\input{figS-heuristics}')
    s = s.replace('\\input{fig15-gap-gini}', '\\input{figS7-gap-gini}')
    s = s.replace('\\input{fig12-signal-robustness}', '\\input{figS5-signal-robustness}')
    return s

for src, dst, hdr in [
    ('appendix-gap-rule.tex', 'si-gap-rule.tex', '% SI Text 1: derivation of the gap rule for constant-returns production functions (Proposition 1, Corollaries 1 and 2, Examples 1 and 2, Fig. S1, Table on the sequential optimum). Generated from appendix-gap-rule.tex by build_si2.py.\n'),
    ('appendix-technology.tex', 'si-technology.tex', '% SI Text 4: robustness to the production function (copy of Appendix C). Generated by build_si2.py.\n'),
    ('appendix-sensitivity.tex', 'si-sensitivity.tex', '% SI Text 5: sensitivity of the value of targeting and of review. Generated from appendix-sensitivity.tex by build_si2.py.\n'),
]:
    s = open(src).read()
    s = '\n'.join(l for l in s.split('\n') if not l.startswith('%'))  # drop the long-version header comments
    s = convert(s).lstrip('\n')
    if dst == 'si-sensitivity.tex':
        s = s.replace('\\label{app:sensitivity}', '\\label{app:sensitivity}\\label{si:sensitivity}', 1)
    open(P + dst, 'w').write(hdr + s)
print('SI copies regenerated')
